
services:
  db:
    # Add port mapping for development database access
    ports:
      - "3306:3306"

  backend:
    ports:
      # Add port mapping for direct API access during development
      - "8000:8000"
    volumes:
      # Mount the backend code for live reloading
      - ./backend:/app
    # Override the command to enable live reloading
    command: >
      sh -c "
        if [ \"$$RUN_ALEMBIC_MIGRATIONS\" = \"true\" ]; then
          alembic upgrade head;
        fi &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    # Override the build to use the development Dockerfile
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: angular_dev_container
    ports:
      # Change port to the Angular development server's default
      - "4200:4200"
    volumes:
      # Mount frontend code for live reloading
      - ./frontend:/app
      # Prevent host's node_modules from overwriting the container's
      - /app/node_modules
    command: npx ng serve --host 0.0.0.0 --port 4200 --poll 500